### ISSUE TITLE
Kernel has died

### ISSUE THREAD

**Issue by tanyapohn** [zdenop/SimpleTesseractPythonWrapper#2]
`SimpleTesseractPythonWrapper.ipynb` appears to have died after I run this line:

`tesseract.TessBaseAPIRecognize(api, ffi.NULL)` 

Also, 

```
tesseract.TessBaseAPIInit3(api, tessdata.encode(), lang.encode())
# gives -1
```

I don't what happens if it relates to Tesseract versions? 

Here's is my libs' versions and setting locale:

```
locale.setlocale(locale.LC_ALL, "C")
## ------------------------------ ##
Tesseract-ocr version 4.0.0-beta.3-249-g607e
leptonica-1.76.0
```

**Comment by zdenop** [comment]
which mean that you have problem to run tesseract...
if `TessBaseAPIInit3` fails there is no reason to try `TessBaseAPIRecognize`.
Try to run tessereact executable from command line at the same folder as you have notebook (with the same parameters used with `TessBaseAPIInit3`) to see exact error message

**Comment by tanyapohn** [comment]
Thank you. 
Now, I can run this `SimpleTesseractPythonWrapper.ipynb` properly after I changed this line code to be my own tessdata path.
To fix this:

```
tessdata = os.path.join(mytessdatapath, "tessdata/")
os.environ['TESSDATA_PREFIX'] = tessdata
```
